/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RunnersRouteImport } from './routes/runners'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RegimeRouteImport } from './routes/regime'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnersRoute = RunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RegimeRoute = RegimeRouteImport.update({
  id: '/regime',
  path: '/regime',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exchanges': typeof ExchangesRoute
  '/feed': typeof FeedRoute
  '/forensics': typeof ForensicsRoute
  '/integrity': typeof IntegrityRoute
  '/intelligence': typeof IntelligenceRoute
  '/positions': typeof PositionsRoute
  '/protection': typeof ProtectionRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/regime': typeof RegimeRoute
  '/risk': typeof RiskRoute
  '/runners': typeof RunnersRoute
  '/scanner': typeof ScannerRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exchanges': typeof ExchangesRoute
  '/feed': typeof FeedRoute
  '/forensics': typeof ForensicsRoute
  '/integrity': typeof IntegrityRoute
  '/intelligence': typeof IntelligenceRoute
  '/positions': typeof PositionsRoute
  '/protection': typeof ProtectionRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/regime': typeof RegimeRoute
  '/risk': typeof RiskRoute
  '/runners': typeof RunnersRoute
  '/scanner': typeof ScannerRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exchanges': typeof ExchangesRoute
  '/feed': typeof FeedRoute
  '/forensics': typeof ForensicsRoute
  '/integrity': typeof IntegrityRoute
  '/intelligence': typeof IntelligenceRoute
  '/positions': typeof PositionsRoute
  '/protection': typeof ProtectionRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/regime': typeof RegimeRoute
  '/risk': typeof RiskRoute
  '/runners': typeof RunnersRoute
  '/scanner': typeof ScannerRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exchanges'
    | '/feed'
    | '/forensics'
    | '/integrity'
    | '/intelligence'
    | '/positions'
    | '/protection'
    | '/queue'
    | '/recovery'
    | '/regime'
    | '/risk'
    | '/runners'
    | '/scanner'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exchanges'
    | '/feed'
    | '/forensics'
    | '/integrity'
    | '/intelligence'
    | '/positions'
    | '/protection'
    | '/queue'
    | '/recovery'
    | '/regime'
    | '/risk'
    | '/runners'
    | '/scanner'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/exchanges'
    | '/feed'
    | '/forensics'
    | '/integrity'
    | '/intelligence'
    | '/positions'
    | '/protection'
    | '/queue'
    | '/recovery'
    | '/regime'
    | '/risk'
    | '/runners'
    | '/scanner'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExchangesRoute: typeof ExchangesRoute
  FeedRoute: typeof FeedRoute
  ForensicsRoute: typeof ForensicsRoute
  IntegrityRoute: typeof IntegrityRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PositionsRoute: typeof PositionsRoute
  ProtectionRoute: typeof ProtectionRoute
  QueueRoute: typeof QueueRoute
  RecoveryRoute: typeof RecoveryRoute
  RegimeRoute: typeof RegimeRoute
  RiskRoute: typeof RiskRoute
  RunnersRoute: typeof RunnersRoute
  ScannerRoute: typeof ScannerRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runners': {
      id: '/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof RunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regime': {
      id: '/regime'
      path: '/regime'
      fullPath: '/regime'
      preLoaderRoute: typeof RegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExchangesRoute: ExchangesRoute,
  FeedRoute: FeedRoute,
  ForensicsRoute: ForensicsRoute,
  IntegrityRoute: IntegrityRoute,
  IntelligenceRoute: IntelligenceRoute,
  PositionsRoute: PositionsRoute,
  ProtectionRoute: ProtectionRoute,
  QueueRoute: QueueRoute,
  RecoveryRoute: RecoveryRoute,
  RegimeRoute: RegimeRoute,
  RiskRoute: RiskRoute,
  RunnersRoute: RunnersRoute,
  ScannerRoute: ScannerRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
